<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/lecture3_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import os
import pandas as pd
import numpy as np

In [3]:
os.getcwd()
os.chdir('/content/drive/MyDrive/My pitch')
os.getcwd()

'/content/drive/MyDrive/My pitch'

In [9]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name='ERPData')
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [10]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [11]:
df.describe()

         Quantity
count   50.000000
mean    57.700000
std     31.887078
min     10.000000
25%     34.000000
50%     54.500000
75%     74.000000
max    152.000000

In [16]:
df.isna().count()

MaterialID    50
Location      50
Quantity      50
dtype: int64